const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');
const plugin = require('tailwindcss/plugin');

module.exports = {
    purge: [
        './_build/**/*.html',
        './src/_site/**/*.md',
        './src/_site/**/*.njk',
        './src/resources/*.js',
    ],
    darkMode: 'class',
    theme: {
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: colors.black,
            white: colors.white,
            neutral: colors.blueGray,
            primary: colors.lightBlue,
            secondary: colors.amber,
        },
        container: {
            center: true,
        },
        screens: {
            sm: '512px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
            '3xl': '1920px',
        },
        minWidth: {
            min: 'min-content',
            max: 'max-content',
            0: '0',
            '1/4': '25%',
            '1/2': '50%',
            '3/4': '75%',
            full: '100%',
            0.5: '0.125rem',
            1: '0.25rem',
            1.5: '0.375rem',
            2: '0.5rem',
            2.5: '0.625rem',
            3: '0.75rem',
            3.5: '0.875rem',
            4: '1rem',
            5: '1.25rem',
            6: '1.5rem',
            7: '1.75rem',
            8: '2rem',
            9: '2.25rem',
            10: '2.5rem',
            11: '2.75rem',
            12: '3rem',
            14: '3.5rem',
            16: '4rem',
            20: '5rem',
            24: '6rem',
            28: '7rem',
            32: '8rem',
            36: '9rem',
            40: '10rem',
            44: '11rem',
            48: '12rem',
            52: '13rem',
            56: '14rem',
            60: '15rem',
            64: '16rem',
            72: '18rem',
            80: '20rem',
            96: '24rem',
        },
        extend: {
            gridTemplateRows: {
                layout: 'auto 1fr auto',
            },
            fontFamily: {
                sans: ['Inter var', ...defaultTheme.fontFamily.sans],
            },
            spacing: {
                54: '12.5rem',
                '-54': '-12.5rem',
                56: '13.5rem',
                '-56': '-13.5rem',
                58: '14.5rem',
                '-58': '-14.5rem',
            },
            inset: {
                half: '50%',
                double: '200%',
                '-half': '-50%',
                '-double': '-200%',
                halfscreenw: '50vw',
                doublescreenw: '200vw',
                '-halfscreenw': '-50vw',
                '-doublescreenw': '-200vw',
                halfscreenh: '50vh',
                doublescreenh: '200vh',
                '-halfscreenh': '-50vh',
                '-doublescreenh': '-200vh',
            },
            translate: {
                half: '50%',
                double: '200%',
                '-half': '-50%',
                '-double': '-200%',
            },
            width: {
                halfscreen: '50vw',
                doublescreen: '200vw',
                '-halfscreen': '-50vw',
                '-doublescreen': '-200vw',
            },
            height: {
                halfscreen: '50vh',
                doublescreen: '200vh',
                '-halfscreen': '-50vh',
                '-doublescreen': '-200vh',
            },
        },
    },
    variants: {
        extend: {
            display: ['dark'],
            textColor: [
                'dark',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            backgroundColor: [
                'dark',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            height: ['dark', 'before', 'after', 'hover_before', 'hover_after'],
            width: ['dark', 'before', 'after', 'hover_before', 'hover_after'],
            boxShadow: [
                'dark',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            position: [
                'dark',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            inset: [
                'dark',
                'focus',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            translate: [
                'dark',
                'focus',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            padding: [
                'dark',
                'focus',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            margin: [
                'dark',
                'focus',
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            zIndex: ['before', 'after', 'hover_before', 'hover_after'],
            borderRadius: ['before', 'after', 'hover_before', 'hover_after'],
            transitionDuration: [
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            transitionTimingFunction: [
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
            transitionProperty: [
                'before',
                'after',
                'hover_before',
                'hover_after',
            ],
        },
    },
    plugins: [
        require('tailwindcss-debug-screens'),
        require('@tailwindcss/forms'),
        require('@tailwindcss/line-clamp'),
        require('@tailwindcss/typography'),
        require('tailwindcss-skip-link')(),
        require('tailwindcss-css-filters'),
        require('tailwindcss-skip-link'),
        require('tailwindcss-blend-mode')(),
        require('tailwindcss-textshadow'),
        require('tailwindcss-pseudo-elements'),
        plugin(function ({ addUtilities }) {
            addUtilities(
                {
                    '.empty-content': {
                        content: "''",
                    },
                },
                ['before', 'after', 'hover_before', 'hover_after']
            );
        }),
    ],
};
